// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Conv2d_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        kernel_address0,
        kernel_ce0,
        kernel_q0,
        out_matrix_address0,
        out_matrix_ce0,
        out_matrix_we0,
        out_matrix_d0,
        conv_out_1_address0,
        conv_out_1_ce0,
        conv_out_1_q0
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_pp0_stage0 = 7'd4;
parameter    ap_ST_fsm_pp0_stage1 = 7'd8;
parameter    ap_ST_fsm_pp0_stage2 = 7'd16;
parameter    ap_ST_fsm_pp0_stage3 = 7'd32;
parameter    ap_ST_fsm_state12 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] kernel_address0;
output   kernel_ce0;
input  [31:0] kernel_q0;
output  [3:0] out_matrix_address0;
output   out_matrix_ce0;
output   out_matrix_we0;
output  [31:0] out_matrix_d0;
output  [9:0] conv_out_1_address0;
output   conv_out_1_ce0;
input  [31:0] conv_out_1_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg kernel_ce0;
reg[3:0] out_matrix_address0;
reg out_matrix_ce0;
reg out_matrix_we0;
reg[31:0] out_matrix_d0;
reg conv_out_1_ce0;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [3:0] indvar_flatten_reg_144;
reg   [2:0] col_0_reg_155;
reg   [31:0] empty_reg_164;
reg   [2:0] row_0_reg_176;
wire   [0:0] icmp_ln31_fu_217_p2;
wire    ap_CS_fsm_state2;
wire   [3:0] add_ln31_fu_223_p2;
reg   [3:0] add_ln31_reg_509;
wire   [2:0] indvars_iv_mid2_fu_241_p3;
reg   [2:0] indvars_iv_mid2_reg_514;
wire   [1:0] row_mid2_fu_249_p3;
reg   [1:0] row_mid2_reg_520;
wire   [1:0] col_cast7_mid2_v_fu_257_p3;
reg   [1:0] col_cast7_mid2_v_reg_525;
wire   [2:0] col_cast7_mid2_fu_265_p1;
wire   [3:0] col_cast_mid2_fu_273_p1;
reg   [3:0] col_cast_mid2_reg_535;
wire   [2:0] row_cast4_fu_307_p1;
reg   [2:0] row_cast4_reg_540;
wire   [7:0] row_cast_fu_311_p1;
reg   [7:0] row_cast_reg_546;
reg   [3:0] out_matrix_addr_reg_551;
wire   [0:0] icmp_ln34_fu_360_p2;
reg   [0:0] icmp_ln34_reg_556;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state3_pp0_stage0_iter0;
wire    ap_block_state7_pp0_stage0_iter1;
wire    ap_block_state11_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln34_reg_556_pp0_iter1_reg;
wire   [3:0] add_ln34_fu_366_p2;
reg   [3:0] add_ln34_reg_560;
reg    ap_enable_reg_pp0_iter0;
wire   [2:0] row_0_mid2_fu_383_p3;
reg   [2:0] row_0_mid2_reg_565;
wire   [2:0] sub_ln36_6_mid2_v_v_s_fu_428_p3;
reg   [2:0] sub_ln36_6_mid2_v_v_s_reg_570;
reg   [31:0] conv_out_1_load_reg_585;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state4_pp0_stage1_iter0;
wire    ap_block_state8_pp0_stage1_iter1;
wire    ap_block_pp0_stage1_11001;
reg   [31:0] kernel_load_reg_590;
wire   [2:0] row_6_fu_482_p2;
reg   [2:0] row_6_reg_595;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state6_pp0_stage3_iter0;
wire    ap_block_state10_pp0_stage3_iter1;
wire    ap_block_pp0_stage3_11001;
wire   [31:0] grp_fu_191_p2;
reg   [31:0] tmp_reg_600;
wire   [31:0] grp_fu_185_p2;
reg    ap_enable_reg_pp0_iter2;
wire   [1:0] j_fu_487_p2;
wire    ap_CS_fsm_state12;
wire   [2:0] add_ln32_fu_492_p2;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage3_subdone;
reg   [3:0] indvar_flatten7_reg_100;
reg   [1:0] col_reg_111;
reg   [2:0] indvars_iv_reg_122;
reg   [1:0] row_reg_133;
reg   [3:0] ap_phi_mux_indvar_flatten_phi_fu_148_p4;
wire    ap_block_pp0_stage0;
reg   [2:0] ap_phi_mux_col_0_phi_fu_158_p4;
reg   [2:0] ap_phi_mux_row_0_phi_fu_179_p4;
wire   [63:0] zext_ln33_fu_325_p1;
wire   [63:0] zext_ln36_fu_467_p1;
wire  signed [63:0] sext_ln36_1_fu_477_p1;
wire    ap_block_pp0_stage1;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2;
wire   [3:0] shl_ln_fu_199_p3;
wire   [4:0] zext_ln33_8_fu_207_p1;
wire   [4:0] col_cast6_fu_195_p1;
wire   [0:0] icmp_ln32_fu_235_p2;
wire   [1:0] i_fu_229_p2;
wire   [3:0] shl_ln33_mid1_fu_277_p3;
wire   [4:0] zext_ln33_16_fu_285_p1;
wire   [4:0] col_cast6_mid1_fu_269_p1;
wire   [4:0] sub_ln33_4_fu_289_p2;
wire   [4:0] sub_ln33_fu_211_p2;
wire   [4:0] sub_ln33_mid2_fu_295_p3;
wire   [4:0] row_cast5_fu_303_p1;
wire   [4:0] add_ln33_fu_315_p2;
wire  signed [31:0] sext_ln33_fu_321_p1;
wire   [7:0] shl_ln7_fu_330_p3;
wire   [4:0] shl_ln36_8_fu_342_p3;
wire   [8:0] zext_ln36_2_fu_338_p1;
wire   [8:0] zext_ln36_3_fu_350_p1;
wire   [0:0] icmp_ln35_fu_378_p2;
wire   [2:0] col_8_fu_372_p2;
wire   [7:0] shl_ln36_mid1_fu_390_p3;
wire   [4:0] shl_ln36_8_mid1_fu_402_p3;
wire   [8:0] zext_ln36_4_fu_398_p1;
wire   [8:0] zext_ln36_5_fu_410_p1;
wire   [8:0] sub_ln36_fu_414_p2;
wire   [8:0] sub_ln36_10_fu_354_p2;
wire   [3:0] sub_ln36_6_mid2_v_v_1_fu_436_p1;
wire  signed [3:0] sub_ln36_6_mid2_v_v_2_fu_440_p2;
wire   [8:0] sub_ln36_10_mid2_fu_420_p3;
wire   [8:0] row_0_cast_mid2_cast_fu_453_p1;
wire   [8:0] add_ln36_fu_457_p2;
wire  signed [31:0] sext_ln36_2_fu_463_p1;
wire   [7:0] row_0_cast1_mid2_cas_fu_449_p1;
wire  signed [7:0] grp_fu_497_p3;
(* use_dsp48 = "no" *) wire   [7:0] add_ln36_2_fu_472_p2;
wire    ap_block_pp0_stage3;
wire   [5:0] grp_fu_497_p1;
wire   [1:0] grp_fu_497_p2;
reg   [6:0] ap_NS_fsm;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_state5_pp0_stage2_iter0;
wire    ap_block_state9_pp0_stage2_iter1;
wire    ap_block_pp0_stage2_subdone;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

forw_back_fadd_32bkb #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
forw_back_fadd_32bkb_U70(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(empty_reg_164),
    .din1(tmp_reg_600),
    .ce(1'b1),
    .dout(grp_fu_185_p2)
);

forw_back_fmul_32cud #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
forw_back_fmul_32cud_U71(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(conv_out_1_load_reg_585),
    .din1(kernel_load_reg_590),
    .ce(1'b1),
    .dout(grp_fu_191_p2)
);

forw_back_mac_mulmb6 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
forw_back_mac_mulmb6_U72(
    .din0(sub_ln36_6_mid2_v_v_2_fu_440_p2),
    .din1(grp_fu_497_p1),
    .din2(grp_fu_497_p2),
    .dout(grp_fu_497_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((icmp_ln31_fu_217_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone)))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((icmp_ln31_fu_217_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln34_reg_556 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        col_0_reg_155 <= sub_ln36_6_mid2_v_v_s_reg_570;
    end else if (((icmp_ln31_fu_217_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        col_0_reg_155 <= col_cast7_mid2_fu_265_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        col_reg_111 <= col_cast7_mid2_v_reg_525;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        col_reg_111 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln34_reg_556_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        empty_reg_164 <= grp_fu_185_p2;
    end else if (((icmp_ln31_fu_217_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        empty_reg_164 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        indvar_flatten7_reg_100 <= add_ln31_reg_509;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten7_reg_100 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln34_reg_556 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        indvar_flatten_reg_144 <= add_ln34_reg_560;
    end else if (((icmp_ln31_fu_217_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        indvar_flatten_reg_144 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        indvars_iv_reg_122 <= add_ln32_fu_492_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvars_iv_reg_122 <= 3'd3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln34_reg_556 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        row_0_reg_176 <= row_6_reg_595;
    end else if (((icmp_ln31_fu_217_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        row_0_reg_176 <= row_cast4_fu_307_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        row_reg_133 <= j_fu_487_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        row_reg_133 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln31_reg_509 <= add_ln31_fu_223_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        add_ln34_reg_560 <= add_ln34_fu_366_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln31_fu_217_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        col_cast7_mid2_v_reg_525 <= col_cast7_mid2_v_fu_257_p3;
        col_cast_mid2_reg_535[1 : 0] <= col_cast_mid2_fu_273_p1[1 : 0];
        indvars_iv_mid2_reg_514 <= indvars_iv_mid2_fu_241_p3;
        out_matrix_addr_reg_551 <= zext_ln33_fu_325_p1;
        row_cast4_reg_540[1 : 0] <= row_cast4_fu_307_p1[1 : 0];
        row_cast_reg_546[1 : 0] <= row_cast_fu_311_p1[1 : 0];
        row_mid2_reg_520 <= row_mid2_fu_249_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln34_reg_556 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        conv_out_1_load_reg_585 <= conv_out_1_q0;
        kernel_load_reg_590 <= kernel_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln34_reg_556 <= icmp_ln34_fu_360_p2;
        icmp_ln34_reg_556_pp0_iter1_reg <= icmp_ln34_reg_556;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln34_fu_360_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_0_mid2_reg_565 <= row_0_mid2_fu_383_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln34_reg_556 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        row_6_reg_595 <= row_6_fu_482_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln34_fu_360_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        sub_ln36_6_mid2_v_v_s_reg_570 <= sub_ln36_6_mid2_v_v_s_fu_428_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln34_reg_556 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_reg_600 <= grp_fu_191_p2;
    end
end

always @ (*) begin
    if ((icmp_ln34_fu_360_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln31_fu_217_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_reg_556 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_mux_col_0_phi_fu_158_p4 = sub_ln36_6_mid2_v_v_s_reg_570;
    end else begin
        ap_phi_mux_col_0_phi_fu_158_p4 = col_0_reg_155;
    end
end

always @ (*) begin
    if (((icmp_ln34_reg_556 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_mux_indvar_flatten_phi_fu_148_p4 = add_ln34_reg_560;
    end else begin
        ap_phi_mux_indvar_flatten_phi_fu_148_p4 = indvar_flatten_reg_144;
    end
end

always @ (*) begin
    if (((icmp_ln34_reg_556 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_mux_row_0_phi_fu_179_p4 = row_6_reg_595;
    end else begin
        ap_phi_mux_row_0_phi_fu_179_p4 = row_0_reg_176;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_217_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        conv_out_1_ce0 = 1'b1;
    end else begin
        conv_out_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        kernel_ce0 = 1'b1;
    end else begin
        kernel_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        out_matrix_address0 = out_matrix_addr_reg_551;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_matrix_address0 = zext_ln33_fu_325_p1;
    end else begin
        out_matrix_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        out_matrix_ce0 = 1'b1;
    end else begin
        out_matrix_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        out_matrix_d0 = grp_fu_185_p2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_matrix_d0 = 32'd0;
    end else begin
        out_matrix_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln34_reg_556_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((icmp_ln31_fu_217_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        out_matrix_we0 = 1'b1;
    end else begin
        out_matrix_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln31_fu_217_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln34_fu_360_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)) & ~((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((icmp_ln34_fu_360_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln31_fu_223_p2 = (indvar_flatten7_reg_100 + 4'd1);

assign add_ln32_fu_492_p2 = (indvars_iv_mid2_reg_514 + 3'd1);

assign add_ln33_fu_315_p2 = (sub_ln33_mid2_fu_295_p3 + row_cast5_fu_303_p1);

assign add_ln34_fu_366_p2 = (ap_phi_mux_indvar_flatten_phi_fu_148_p4 + 4'd1);

assign add_ln36_2_fu_472_p2 = ($signed(row_0_cast1_mid2_cas_fu_449_p1) + $signed(grp_fu_497_p3));

assign add_ln36_fu_457_p2 = (sub_ln36_10_mid2_fu_420_p3 + row_0_cast_mid2_cast_fu_453_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign col_8_fu_372_p2 = (ap_phi_mux_col_0_phi_fu_158_p4 + 3'd1);

assign col_cast6_fu_195_p1 = col_reg_111;

assign col_cast6_mid1_fu_269_p1 = i_fu_229_p2;

assign col_cast7_mid2_fu_265_p1 = col_cast7_mid2_v_fu_257_p3;

assign col_cast7_mid2_v_fu_257_p3 = ((icmp_ln32_fu_235_p2[0:0] === 1'b1) ? i_fu_229_p2 : col_reg_111);

assign col_cast_mid2_fu_273_p1 = col_cast7_mid2_v_fu_257_p3;

assign conv_out_1_address0 = zext_ln36_fu_467_p1;

assign grp_fu_497_p1 = 8'd26;

assign grp_fu_497_p2 = row_cast_reg_546;

assign i_fu_229_p2 = (col_reg_111 + 2'd1);

assign icmp_ln31_fu_217_p2 = ((indvar_flatten7_reg_100 == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln32_fu_235_p2 = ((indvars_iv_reg_122 == 3'd6) ? 1'b1 : 1'b0);

assign icmp_ln34_fu_360_p2 = ((ap_phi_mux_indvar_flatten_phi_fu_148_p4 == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_378_p2 = ((ap_phi_mux_row_0_phi_fu_179_p4 == indvars_iv_mid2_reg_514) ? 1'b1 : 1'b0);

assign indvars_iv_mid2_fu_241_p3 = ((icmp_ln32_fu_235_p2[0:0] === 1'b1) ? 3'd3 : indvars_iv_reg_122);

assign j_fu_487_p2 = (row_mid2_reg_520 + 2'd1);

assign kernel_address0 = sext_ln36_1_fu_477_p1;

assign row_0_cast1_mid2_cas_fu_449_p1 = row_0_mid2_fu_383_p3;

assign row_0_cast_mid2_cast_fu_453_p1 = row_0_mid2_fu_383_p3;

assign row_0_mid2_fu_383_p3 = ((icmp_ln35_fu_378_p2[0:0] === 1'b1) ? row_cast4_reg_540 : ap_phi_mux_row_0_phi_fu_179_p4);

assign row_6_fu_482_p2 = (row_0_mid2_reg_565 + 3'd1);

assign row_cast4_fu_307_p1 = row_mid2_fu_249_p3;

assign row_cast5_fu_303_p1 = row_mid2_fu_249_p3;

assign row_cast_fu_311_p1 = row_mid2_fu_249_p3;

assign row_mid2_fu_249_p3 = ((icmp_ln32_fu_235_p2[0:0] === 1'b1) ? 2'd0 : row_reg_133);

assign sext_ln33_fu_321_p1 = $signed(add_ln33_fu_315_p2);

assign sext_ln36_1_fu_477_p1 = $signed(add_ln36_2_fu_472_p2);

assign sext_ln36_2_fu_463_p1 = $signed(add_ln36_fu_457_p2);

assign shl_ln33_mid1_fu_277_p3 = {{i_fu_229_p2}, {2'd0}};

assign shl_ln36_8_fu_342_p3 = {{ap_phi_mux_col_0_phi_fu_158_p4}, {2'd0}};

assign shl_ln36_8_mid1_fu_402_p3 = {{col_8_fu_372_p2}, {2'd0}};

assign shl_ln36_mid1_fu_390_p3 = {{col_8_fu_372_p2}, {5'd0}};

assign shl_ln7_fu_330_p3 = {{ap_phi_mux_col_0_phi_fu_158_p4}, {5'd0}};

assign shl_ln_fu_199_p3 = {{col_reg_111}, {2'd0}};

assign sub_ln33_4_fu_289_p2 = (zext_ln33_16_fu_285_p1 - col_cast6_mid1_fu_269_p1);

assign sub_ln33_fu_211_p2 = (zext_ln33_8_fu_207_p1 - col_cast6_fu_195_p1);

assign sub_ln33_mid2_fu_295_p3 = ((icmp_ln32_fu_235_p2[0:0] === 1'b1) ? sub_ln33_4_fu_289_p2 : sub_ln33_fu_211_p2);

assign sub_ln36_10_fu_354_p2 = (zext_ln36_2_fu_338_p1 - zext_ln36_3_fu_350_p1);

assign sub_ln36_10_mid2_fu_420_p3 = ((icmp_ln35_fu_378_p2[0:0] === 1'b1) ? sub_ln36_fu_414_p2 : sub_ln36_10_fu_354_p2);

assign sub_ln36_6_mid2_v_v_1_fu_436_p1 = sub_ln36_6_mid2_v_v_s_fu_428_p3;

assign sub_ln36_6_mid2_v_v_2_fu_440_p2 = (sub_ln36_6_mid2_v_v_1_fu_436_p1 - col_cast_mid2_reg_535);

assign sub_ln36_6_mid2_v_v_s_fu_428_p3 = ((icmp_ln35_fu_378_p2[0:0] === 1'b1) ? col_8_fu_372_p2 : ap_phi_mux_col_0_phi_fu_158_p4);

assign sub_ln36_fu_414_p2 = (zext_ln36_4_fu_398_p1 - zext_ln36_5_fu_410_p1);

assign zext_ln33_16_fu_285_p1 = shl_ln33_mid1_fu_277_p3;

assign zext_ln33_8_fu_207_p1 = shl_ln_fu_199_p3;

assign zext_ln33_fu_325_p1 = $unsigned(sext_ln33_fu_321_p1);

assign zext_ln36_2_fu_338_p1 = shl_ln7_fu_330_p3;

assign zext_ln36_3_fu_350_p1 = shl_ln36_8_fu_342_p3;

assign zext_ln36_4_fu_398_p1 = shl_ln36_mid1_fu_390_p3;

assign zext_ln36_5_fu_410_p1 = shl_ln36_8_mid1_fu_402_p3;

assign zext_ln36_fu_467_p1 = $unsigned(sext_ln36_2_fu_463_p1);

always @ (posedge ap_clk) begin
    col_cast_mid2_reg_535[3:2] <= 2'b00;
    row_cast4_reg_540[2] <= 1'b0;
    row_cast_reg_546[7:2] <= 6'b000000;
end

endmodule //Conv2d_2
