// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Conv2d_3.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Conv2d_3::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Conv2d_3::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<16> Conv2d_3::ap_ST_fsm_state1 = "1";
const sc_lv<16> Conv2d_3::ap_ST_fsm_state2 = "10";
const sc_lv<16> Conv2d_3::ap_ST_fsm_state3 = "100";
const sc_lv<16> Conv2d_3::ap_ST_fsm_state4 = "1000";
const sc_lv<16> Conv2d_3::ap_ST_fsm_state5 = "10000";
const sc_lv<16> Conv2d_3::ap_ST_fsm_state6 = "100000";
const sc_lv<16> Conv2d_3::ap_ST_fsm_state7 = "1000000";
const sc_lv<16> Conv2d_3::ap_ST_fsm_state8 = "10000000";
const sc_lv<16> Conv2d_3::ap_ST_fsm_state9 = "100000000";
const sc_lv<16> Conv2d_3::ap_ST_fsm_state10 = "1000000000";
const sc_lv<16> Conv2d_3::ap_ST_fsm_state11 = "10000000000";
const sc_lv<16> Conv2d_3::ap_ST_fsm_state12 = "100000000000";
const sc_lv<16> Conv2d_3::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<16> Conv2d_3::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<16> Conv2d_3::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<16> Conv2d_3::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<32> Conv2d_3::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> Conv2d_3::ap_const_lv32_1 = "1";
const sc_lv<1> Conv2d_3::ap_const_lv1_0 = "0";
const sc_lv<32> Conv2d_3::ap_const_lv32_2 = "10";
const sc_lv<32> Conv2d_3::ap_const_lv32_3 = "11";
const sc_lv<1> Conv2d_3::ap_const_lv1_1 = "1";
const sc_lv<32> Conv2d_3::ap_const_lv32_4 = "100";
const sc_lv<32> Conv2d_3::ap_const_lv32_5 = "101";
const sc_lv<32> Conv2d_3::ap_const_lv32_6 = "110";
const sc_lv<32> Conv2d_3::ap_const_lv32_9 = "1001";
const sc_lv<32> Conv2d_3::ap_const_lv32_E = "1110";
const sc_lv<4> Conv2d_3::ap_const_lv4_0 = "0000";
const sc_lv<32> Conv2d_3::ap_const_lv32_F = "1111";
const sc_lv<32> Conv2d_3::ap_const_lv32_A = "1010";
const sc_lv<4> Conv2d_3::ap_const_lv4_C = "1100";
const sc_lv<4> Conv2d_3::ap_const_lv4_1 = "1";
const sc_lv<2> Conv2d_3::ap_const_lv2_0 = "00";
const sc_lv<4> Conv2d_3::ap_const_lv4_3 = "11";
const bool Conv2d_3::ap_const_boolean_1 = true;

Conv2d_3::Conv2d_3(sc_module_name name) : sc_module(name), mVcdFile(0) {
    forw_back_fadd_32bkb_U15 = new forw_back_fadd_32bkb<1,5,32,32,32>("forw_back_fadd_32bkb_U15");
    forw_back_fadd_32bkb_U15->clk(ap_clk);
    forw_back_fadd_32bkb_U15->reset(ap_rst);
    forw_back_fadd_32bkb_U15->din0(empty_149_reg_128);
    forw_back_fadd_32bkb_U15->din1(tmp_reg_439);
    forw_back_fadd_32bkb_U15->ce(ap_var_for_const0);
    forw_back_fadd_32bkb_U15->dout(grp_fu_149_p2);
    forw_back_fmul_32cud_U16 = new forw_back_fmul_32cud<1,4,32,32,32>("forw_back_fmul_32cud_U16");
    forw_back_fmul_32cud_U16->clk(ap_clk);
    forw_back_fmul_32cud_U16->reset(ap_rst);
    forw_back_fmul_32cud_U16->din0(input_matrix_load_reg_424);
    forw_back_fmul_32cud_U16->din1(kernel_q0);
    forw_back_fmul_32cud_U16->ce(ap_var_for_const0);
    forw_back_fmul_32cud_U16->dout(grp_fu_154_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln30_fu_235_p2);
    sensitive << ( sub_ln30_reg_354 );
    sensitive << ( zext_ln32_fu_215_p1 );

    SC_METHOD(thread_add_ln31_fu_205_p2);
    sensitive << ( col_reg_84 );

    SC_METHOD(thread_add_ln32_fu_249_p2);
    sensitive << ( row_reg_95 );

    SC_METHOD(thread_add_ln33_2_fu_319_p2);
    sensitive << ( sub_ln33_2_reg_396 );
    sensitive << ( row_0_reg_140 );

    SC_METHOD(thread_add_ln33_fu_309_p2);
    sensitive << ( sub_ln33_4_reg_391 );
    sensitive << ( row_0_reg_140 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln28_fu_163_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln28_fu_163_p2 );

    SC_METHOD(thread_col_4_fu_330_p2);
    sensitive << ( col_0_reg_118 );

    SC_METHOD(thread_col_cast3_fu_159_p1);
    sensitive << ( col_reg_84 );

    SC_METHOD(thread_i_fu_169_p2);
    sensitive << ( col_reg_84 );

    SC_METHOD(thread_icmp_ln28_fu_163_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( col_reg_84 );

    SC_METHOD(thread_icmp_ln29_fu_223_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( row_reg_95 );

    SC_METHOD(thread_icmp_ln31_fu_259_p2);
    sensitive << ( zext_ln31_reg_359 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( col_0_reg_118 );

    SC_METHOD(thread_icmp_ln32_fu_304_p2);
    sensitive << ( zext_ln32_4_reg_383 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( row_0_reg_140 );

    SC_METHOD(thread_input_matrix_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( sext_ln33_fu_314_p1 );

    SC_METHOD(thread_input_matrix_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_j_fu_229_p2);
    sensitive << ( row_reg_95 );

    SC_METHOD(thread_kernel_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( sext_ln33_1_fu_336_p1 );

    SC_METHOD(thread_kernel_ce0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_out_matrix_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( out_matrix_addr_reg_378 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( zext_ln30_fu_244_p1 );

    SC_METHOD(thread_out_matrix_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_out_matrix_d0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_s_reg_444 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_out_matrix_we0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln29_fu_223_p2 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_row_4_fu_324_p2);
    sensitive << ( row_0_reg_140 );

    SC_METHOD(thread_sext_ln30_fu_240_p1);
    sensitive << ( add_ln30_fu_235_p2 );

    SC_METHOD(thread_sext_ln33_1_fu_336_p1);
    sensitive << ( add_ln33_2_reg_409 );

    SC_METHOD(thread_sext_ln33_fu_314_p1);
    sensitive << ( add_ln33_fu_309_p2 );

    SC_METHOD(thread_shl_ln30_2_fu_187_p3);
    sensitive << ( col_reg_84 );

    SC_METHOD(thread_shl_ln33_3_fu_270_p2);
    sensitive << ( col_0_reg_118 );

    SC_METHOD(thread_shl_ln33_4_fu_287_p2);
    sensitive << ( sub_ln33_fu_282_p2 );

    SC_METHOD(thread_shl_ln33_fu_264_p2);
    sensitive << ( col_0_reg_118 );

    SC_METHOD(thread_shl_ln_fu_175_p3);
    sensitive << ( col_reg_84 );

    SC_METHOD(thread_sub_ln30_fu_199_p2);
    sensitive << ( zext_ln30_3_fu_183_p1 );
    sensitive << ( zext_ln30_4_fu_195_p1 );

    SC_METHOD(thread_sub_ln33_2_fu_299_p2);
    sensitive << ( zext_ln32_3_reg_364 );
    sensitive << ( sub_ln33_5_fu_293_p2 );

    SC_METHOD(thread_sub_ln33_4_fu_276_p2);
    sensitive << ( shl_ln33_fu_264_p2 );
    sensitive << ( shl_ln33_3_fu_270_p2 );

    SC_METHOD(thread_sub_ln33_5_fu_293_p2);
    sensitive << ( sub_ln33_fu_282_p2 );
    sensitive << ( shl_ln33_4_fu_287_p2 );

    SC_METHOD(thread_sub_ln33_fu_282_p2);
    sensitive << ( col_cast3_reg_340 );
    sensitive << ( col_0_reg_118 );

    SC_METHOD(thread_zext_ln30_3_fu_183_p1);
    sensitive << ( shl_ln_fu_175_p3 );

    SC_METHOD(thread_zext_ln30_4_fu_195_p1);
    sensitive << ( shl_ln30_2_fu_187_p3 );

    SC_METHOD(thread_zext_ln30_fu_244_p1);
    sensitive << ( sext_ln30_fu_240_p1 );

    SC_METHOD(thread_zext_ln31_fu_211_p1);
    sensitive << ( add_ln31_fu_205_p2 );

    SC_METHOD(thread_zext_ln32_3_fu_219_p1);
    sensitive << ( row_reg_95 );

    SC_METHOD(thread_zext_ln32_4_fu_255_p1);
    sensitive << ( add_ln32_fu_249_p2 );

    SC_METHOD(thread_zext_ln32_fu_215_p1);
    sensitive << ( row_reg_95 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln28_fu_163_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln29_fu_223_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln31_fu_259_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln32_fu_304_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "0000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Conv2d_3_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_matrix_address0, "(port)input_matrix_address0");
    sc_trace(mVcdFile, input_matrix_ce0, "(port)input_matrix_ce0");
    sc_trace(mVcdFile, input_matrix_q0, "(port)input_matrix_q0");
    sc_trace(mVcdFile, kernel_address0, "(port)kernel_address0");
    sc_trace(mVcdFile, kernel_ce0, "(port)kernel_ce0");
    sc_trace(mVcdFile, kernel_q0, "(port)kernel_q0");
    sc_trace(mVcdFile, out_matrix_address0, "(port)out_matrix_address0");
    sc_trace(mVcdFile, out_matrix_ce0, "(port)out_matrix_ce0");
    sc_trace(mVcdFile, out_matrix_we0, "(port)out_matrix_we0");
    sc_trace(mVcdFile, out_matrix_d0, "(port)out_matrix_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, col_cast3_fu_159_p1, "col_cast3_fu_159_p1");
    sc_trace(mVcdFile, col_cast3_reg_340, "col_cast3_reg_340");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_fu_169_p2, "i_fu_169_p2");
    sc_trace(mVcdFile, i_reg_349, "i_reg_349");
    sc_trace(mVcdFile, sub_ln30_fu_199_p2, "sub_ln30_fu_199_p2");
    sc_trace(mVcdFile, sub_ln30_reg_354, "sub_ln30_reg_354");
    sc_trace(mVcdFile, icmp_ln28_fu_163_p2, "icmp_ln28_fu_163_p2");
    sc_trace(mVcdFile, zext_ln31_fu_211_p1, "zext_ln31_fu_211_p1");
    sc_trace(mVcdFile, zext_ln31_reg_359, "zext_ln31_reg_359");
    sc_trace(mVcdFile, zext_ln32_3_fu_219_p1, "zext_ln32_3_fu_219_p1");
    sc_trace(mVcdFile, zext_ln32_3_reg_364, "zext_ln32_3_reg_364");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, j_fu_229_p2, "j_fu_229_p2");
    sc_trace(mVcdFile, j_reg_373, "j_reg_373");
    sc_trace(mVcdFile, out_matrix_addr_reg_378, "out_matrix_addr_reg_378");
    sc_trace(mVcdFile, icmp_ln29_fu_223_p2, "icmp_ln29_fu_223_p2");
    sc_trace(mVcdFile, zext_ln32_4_fu_255_p1, "zext_ln32_4_fu_255_p1");
    sc_trace(mVcdFile, zext_ln32_4_reg_383, "zext_ln32_4_reg_383");
    sc_trace(mVcdFile, sub_ln33_4_fu_276_p2, "sub_ln33_4_fu_276_p2");
    sc_trace(mVcdFile, sub_ln33_4_reg_391, "sub_ln33_4_reg_391");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, icmp_ln31_fu_259_p2, "icmp_ln31_fu_259_p2");
    sc_trace(mVcdFile, sub_ln33_2_fu_299_p2, "sub_ln33_2_fu_299_p2");
    sc_trace(mVcdFile, sub_ln33_2_reg_396, "sub_ln33_2_reg_396");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, icmp_ln32_fu_304_p2, "icmp_ln32_fu_304_p2");
    sc_trace(mVcdFile, add_ln33_2_fu_319_p2, "add_ln33_2_fu_319_p2");
    sc_trace(mVcdFile, add_ln33_2_reg_409, "add_ln33_2_reg_409");
    sc_trace(mVcdFile, row_4_fu_324_p2, "row_4_fu_324_p2");
    sc_trace(mVcdFile, row_4_reg_414, "row_4_reg_414");
    sc_trace(mVcdFile, col_4_fu_330_p2, "col_4_fu_330_p2");
    sc_trace(mVcdFile, input_matrix_load_reg_424, "input_matrix_load_reg_424");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, grp_fu_154_p2, "grp_fu_154_p2");
    sc_trace(mVcdFile, tmp_reg_439, "tmp_reg_439");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, grp_fu_149_p2, "grp_fu_149_p2");
    sc_trace(mVcdFile, tmp_s_reg_444, "tmp_s_reg_444");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, col_reg_84, "col_reg_84");
    sc_trace(mVcdFile, row_reg_95, "row_reg_95");
    sc_trace(mVcdFile, empty_148_reg_106, "empty_148_reg_106");
    sc_trace(mVcdFile, col_0_reg_118, "col_0_reg_118");
    sc_trace(mVcdFile, empty_149_reg_128, "empty_149_reg_128");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, row_0_reg_140, "row_0_reg_140");
    sc_trace(mVcdFile, zext_ln30_fu_244_p1, "zext_ln30_fu_244_p1");
    sc_trace(mVcdFile, sext_ln33_fu_314_p1, "sext_ln33_fu_314_p1");
    sc_trace(mVcdFile, sext_ln33_1_fu_336_p1, "sext_ln33_1_fu_336_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, shl_ln_fu_175_p3, "shl_ln_fu_175_p3");
    sc_trace(mVcdFile, shl_ln30_2_fu_187_p3, "shl_ln30_2_fu_187_p3");
    sc_trace(mVcdFile, zext_ln30_3_fu_183_p1, "zext_ln30_3_fu_183_p1");
    sc_trace(mVcdFile, zext_ln30_4_fu_195_p1, "zext_ln30_4_fu_195_p1");
    sc_trace(mVcdFile, add_ln31_fu_205_p2, "add_ln31_fu_205_p2");
    sc_trace(mVcdFile, zext_ln32_fu_215_p1, "zext_ln32_fu_215_p1");
    sc_trace(mVcdFile, add_ln30_fu_235_p2, "add_ln30_fu_235_p2");
    sc_trace(mVcdFile, sext_ln30_fu_240_p1, "sext_ln30_fu_240_p1");
    sc_trace(mVcdFile, add_ln32_fu_249_p2, "add_ln32_fu_249_p2");
    sc_trace(mVcdFile, shl_ln33_fu_264_p2, "shl_ln33_fu_264_p2");
    sc_trace(mVcdFile, shl_ln33_3_fu_270_p2, "shl_ln33_3_fu_270_p2");
    sc_trace(mVcdFile, sub_ln33_fu_282_p2, "sub_ln33_fu_282_p2");
    sc_trace(mVcdFile, shl_ln33_4_fu_287_p2, "shl_ln33_4_fu_287_p2");
    sc_trace(mVcdFile, sub_ln33_5_fu_293_p2, "sub_ln33_5_fu_293_p2");
    sc_trace(mVcdFile, add_ln33_fu_309_p2, "add_ln33_fu_309_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

Conv2d_3::~Conv2d_3() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete forw_back_fadd_32bkb_U15;
    delete forw_back_fmul_32cud_U16;
}

void Conv2d_3::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void Conv2d_3::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln32_fu_304_p2.read()))) {
        col_0_reg_118 = col_4_fu_330_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln29_fu_223_p2.read()))) {
        col_0_reg_118 = col_cast3_reg_340.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln29_fu_223_p2.read(), ap_const_lv1_1))) {
        col_reg_84 = i_reg_349.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        col_reg_84 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln32_fu_304_p2.read()))) {
        empty_148_reg_106 = empty_149_reg_128.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln29_fu_223_p2.read()))) {
        empty_148_reg_106 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln31_fu_259_p2.read(), ap_const_lv1_1))) {
        empty_149_reg_128 = empty_148_reg_106.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        empty_149_reg_128 = tmp_s_reg_444.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln31_fu_259_p2.read(), ap_const_lv1_1))) {
        row_0_reg_140 = zext_ln32_3_reg_364.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        row_0_reg_140 = row_4_reg_414.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln31_fu_259_p2.read()))) {
        row_reg_95 = j_reg_373.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln28_fu_163_p2.read(), ap_const_lv1_0))) {
        row_reg_95 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln32_fu_304_p2.read()))) {
        add_ln33_2_reg_409 = add_ln33_2_fu_319_p2.read();
        row_4_reg_414 = row_4_fu_324_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        col_cast3_reg_340 = col_cast3_fu_159_p1.read();
        i_reg_349 = i_fu_169_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        input_matrix_load_reg_424 = input_matrix_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        j_reg_373 = j_fu_229_p2.read();
        zext_ln32_3_reg_364 = zext_ln32_3_fu_219_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln29_fu_223_p2.read()))) {
        out_matrix_addr_reg_378 =  (sc_lv<8>) (zext_ln30_fu_244_p1.read());
        zext_ln32_4_reg_383 = zext_ln32_4_fu_255_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln28_fu_163_p2.read(), ap_const_lv1_0))) {
        sub_ln30_reg_354 = sub_ln30_fu_199_p2.read();
        zext_ln31_reg_359 = zext_ln31_fu_211_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln31_fu_259_p2.read(), ap_const_lv1_1))) {
        sub_ln33_2_reg_396 = sub_ln33_2_fu_299_p2.read();
        sub_ln33_4_reg_391 = sub_ln33_4_fu_276_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        tmp_reg_439 = grp_fu_154_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        tmp_s_reg_444 = grp_fu_149_p2.read();
    }
}

void Conv2d_3::thread_add_ln30_fu_235_p2() {
    add_ln30_fu_235_p2 = (!sub_ln30_reg_354.read().is_01() || !zext_ln32_fu_215_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(sub_ln30_reg_354.read()) + sc_biguint<9>(zext_ln32_fu_215_p1.read()));
}

void Conv2d_3::thread_add_ln31_fu_205_p2() {
    add_ln31_fu_205_p2 = (!col_reg_84.read().is_01() || !ap_const_lv4_3.is_01())? sc_lv<4>(): (sc_biguint<4>(col_reg_84.read()) + sc_biguint<4>(ap_const_lv4_3));
}

void Conv2d_3::thread_add_ln32_fu_249_p2() {
    add_ln32_fu_249_p2 = (!row_reg_95.read().is_01() || !ap_const_lv4_3.is_01())? sc_lv<4>(): (sc_biguint<4>(row_reg_95.read()) + sc_biguint<4>(ap_const_lv4_3));
}

void Conv2d_3::thread_add_ln33_2_fu_319_p2() {
    add_ln33_2_fu_319_p2 = (!sub_ln33_2_reg_396.read().is_01() || !row_0_reg_140.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sub_ln33_2_reg_396.read()) + sc_biguint<32>(row_0_reg_140.read()));
}

void Conv2d_3::thread_add_ln33_fu_309_p2() {
    add_ln33_fu_309_p2 = (!row_0_reg_140.read().is_01() || !sub_ln33_4_reg_391.read().is_01())? sc_lv<32>(): (sc_biguint<32>(row_0_reg_140.read()) + sc_biguint<32>(sub_ln33_4_reg_391.read()));
}

void Conv2d_3::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void Conv2d_3::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void Conv2d_3::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void Conv2d_3::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void Conv2d_3::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void Conv2d_3::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void Conv2d_3::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void Conv2d_3::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void Conv2d_3::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void Conv2d_3::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void Conv2d_3::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void Conv2d_3::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln28_fu_163_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void Conv2d_3::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Conv2d_3::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln28_fu_163_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void Conv2d_3::thread_col_4_fu_330_p2() {
    col_4_fu_330_p2 = (!col_0_reg_118.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(col_0_reg_118.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void Conv2d_3::thread_col_cast3_fu_159_p1() {
    col_cast3_fu_159_p1 = esl_zext<32,4>(col_reg_84.read());
}

void Conv2d_3::thread_i_fu_169_p2() {
    i_fu_169_p2 = (!col_reg_84.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(col_reg_84.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void Conv2d_3::thread_icmp_ln28_fu_163_p2() {
    icmp_ln28_fu_163_p2 = (!col_reg_84.read().is_01() || !ap_const_lv4_C.is_01())? sc_lv<1>(): sc_lv<1>(col_reg_84.read() == ap_const_lv4_C);
}

void Conv2d_3::thread_icmp_ln29_fu_223_p2() {
    icmp_ln29_fu_223_p2 = (!row_reg_95.read().is_01() || !ap_const_lv4_C.is_01())? sc_lv<1>(): sc_lv<1>(row_reg_95.read() == ap_const_lv4_C);
}

void Conv2d_3::thread_icmp_ln31_fu_259_p2() {
    icmp_ln31_fu_259_p2 = (!col_0_reg_118.read().is_01() || !zext_ln31_reg_359.read().is_01())? sc_lv<1>(): (sc_bigint<32>(col_0_reg_118.read()) < sc_bigint<32>(zext_ln31_reg_359.read()));
}

void Conv2d_3::thread_icmp_ln32_fu_304_p2() {
    icmp_ln32_fu_304_p2 = (!row_0_reg_140.read().is_01() || !zext_ln32_4_reg_383.read().is_01())? sc_lv<1>(): (sc_bigint<32>(row_0_reg_140.read()) < sc_bigint<32>(zext_ln32_4_reg_383.read()));
}

void Conv2d_3::thread_input_matrix_address0() {
    input_matrix_address0 =  (sc_lv<8>) (sext_ln33_fu_314_p1.read());
}

void Conv2d_3::thread_input_matrix_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        input_matrix_ce0 = ap_const_logic_1;
    } else {
        input_matrix_ce0 = ap_const_logic_0;
    }
}

void Conv2d_3::thread_j_fu_229_p2() {
    j_fu_229_p2 = (!row_reg_95.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(row_reg_95.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void Conv2d_3::thread_kernel_address0() {
    kernel_address0 =  (sc_lv<4>) (sext_ln33_1_fu_336_p1.read());
}

void Conv2d_3::thread_kernel_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        kernel_ce0 = ap_const_logic_1;
    } else {
        kernel_ce0 = ap_const_logic_0;
    }
}

void Conv2d_3::thread_out_matrix_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        out_matrix_address0 = out_matrix_addr_reg_378.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        out_matrix_address0 =  (sc_lv<8>) (zext_ln30_fu_244_p1.read());
    } else {
        out_matrix_address0 = "XXXXXXXX";
    }
}

void Conv2d_3::thread_out_matrix_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        out_matrix_ce0 = ap_const_logic_1;
    } else {
        out_matrix_ce0 = ap_const_logic_0;
    }
}

void Conv2d_3::thread_out_matrix_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        out_matrix_d0 = tmp_s_reg_444.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        out_matrix_d0 = ap_const_lv32_0;
    } else {
        out_matrix_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void Conv2d_3::thread_out_matrix_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln29_fu_223_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        out_matrix_we0 = ap_const_logic_1;
    } else {
        out_matrix_we0 = ap_const_logic_0;
    }
}

void Conv2d_3::thread_row_4_fu_324_p2() {
    row_4_fu_324_p2 = (!row_0_reg_140.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(row_0_reg_140.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void Conv2d_3::thread_sext_ln30_fu_240_p1() {
    sext_ln30_fu_240_p1 = esl_sext<32,9>(add_ln30_fu_235_p2.read());
}

void Conv2d_3::thread_sext_ln33_1_fu_336_p1() {
    sext_ln33_1_fu_336_p1 = esl_sext<64,32>(add_ln33_2_reg_409.read());
}

void Conv2d_3::thread_sext_ln33_fu_314_p1() {
    sext_ln33_fu_314_p1 = esl_sext<64,32>(add_ln33_fu_309_p2.read());
}

void Conv2d_3::thread_shl_ln30_2_fu_187_p3() {
    shl_ln30_2_fu_187_p3 = esl_concat<4,2>(col_reg_84.read(), ap_const_lv2_0);
}

void Conv2d_3::thread_shl_ln33_3_fu_270_p2() {
    shl_ln33_3_fu_270_p2 = (!ap_const_lv32_1.is_01())? sc_lv<32>(): col_0_reg_118.read() << (unsigned short)ap_const_lv32_1.to_uint();
}

void Conv2d_3::thread_shl_ln33_4_fu_287_p2() {
    shl_ln33_4_fu_287_p2 = (!ap_const_lv32_2.is_01())? sc_lv<32>(): sub_ln33_fu_282_p2.read() << (unsigned short)ap_const_lv32_2.to_uint();
}

void Conv2d_3::thread_shl_ln33_fu_264_p2() {
    shl_ln33_fu_264_p2 = (!ap_const_lv32_4.is_01())? sc_lv<32>(): col_0_reg_118.read() << (unsigned short)ap_const_lv32_4.to_uint();
}

void Conv2d_3::thread_shl_ln_fu_175_p3() {
    shl_ln_fu_175_p3 = esl_concat<4,4>(col_reg_84.read(), ap_const_lv4_0);
}

void Conv2d_3::thread_sub_ln30_fu_199_p2() {
    sub_ln30_fu_199_p2 = (!zext_ln30_3_fu_183_p1.read().is_01() || !zext_ln30_4_fu_195_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(zext_ln30_3_fu_183_p1.read()) - sc_biguint<9>(zext_ln30_4_fu_195_p1.read()));
}

void Conv2d_3::thread_sub_ln33_2_fu_299_p2() {
    sub_ln33_2_fu_299_p2 = (!sub_ln33_5_fu_293_p2.read().is_01() || !zext_ln32_3_reg_364.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sub_ln33_5_fu_293_p2.read()) - sc_biguint<32>(zext_ln32_3_reg_364.read()));
}

void Conv2d_3::thread_sub_ln33_4_fu_276_p2() {
    sub_ln33_4_fu_276_p2 = (!shl_ln33_fu_264_p2.read().is_01() || !shl_ln33_3_fu_270_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(shl_ln33_fu_264_p2.read()) - sc_biguint<32>(shl_ln33_3_fu_270_p2.read()));
}

void Conv2d_3::thread_sub_ln33_5_fu_293_p2() {
    sub_ln33_5_fu_293_p2 = (!shl_ln33_4_fu_287_p2.read().is_01() || !sub_ln33_fu_282_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(shl_ln33_4_fu_287_p2.read()) - sc_biguint<32>(sub_ln33_fu_282_p2.read()));
}

void Conv2d_3::thread_sub_ln33_fu_282_p2() {
    sub_ln33_fu_282_p2 = (!col_0_reg_118.read().is_01() || !col_cast3_reg_340.read().is_01())? sc_lv<32>(): (sc_biguint<32>(col_0_reg_118.read()) - sc_biguint<32>(col_cast3_reg_340.read()));
}

void Conv2d_3::thread_zext_ln30_3_fu_183_p1() {
    zext_ln30_3_fu_183_p1 = esl_zext<9,8>(shl_ln_fu_175_p3.read());
}

void Conv2d_3::thread_zext_ln30_4_fu_195_p1() {
    zext_ln30_4_fu_195_p1 = esl_zext<9,6>(shl_ln30_2_fu_187_p3.read());
}

void Conv2d_3::thread_zext_ln30_fu_244_p1() {
    zext_ln30_fu_244_p1 = esl_zext<64,32>(sext_ln30_fu_240_p1.read());
}

void Conv2d_3::thread_zext_ln31_fu_211_p1() {
    zext_ln31_fu_211_p1 = esl_zext<32,4>(add_ln31_fu_205_p2.read());
}

void Conv2d_3::thread_zext_ln32_3_fu_219_p1() {
    zext_ln32_3_fu_219_p1 = esl_zext<32,4>(row_reg_95.read());
}

void Conv2d_3::thread_zext_ln32_4_fu_255_p1() {
    zext_ln32_4_fu_255_p1 = esl_zext<32,4>(add_ln32_fu_249_p2.read());
}

void Conv2d_3::thread_zext_ln32_fu_215_p1() {
    zext_ln32_fu_215_p1 = esl_zext<9,4>(row_reg_95.read());
}

void Conv2d_3::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln28_fu_163_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln29_fu_223_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln31_fu_259_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln32_fu_304_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
            break;
    }
}

}

