// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _MaxPool2d_HH_
#define _MaxPool2d_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "forw_back_sitofp_dEe.h"
#include "forw_back_fcmp_32eOg.h"

namespace ap_rtl {

struct MaxPool2d : public sc_module {
    // Port declarations 17
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<6> > output_matrix_address0;
    sc_out< sc_logic > output_matrix_ce0;
    sc_out< sc_logic > output_matrix_we0;
    sc_out< sc_lv<32> > output_matrix_d0;
    sc_out< sc_lv<6> > locate_matrix_address0;
    sc_out< sc_logic > locate_matrix_ce0;
    sc_out< sc_logic > locate_matrix_we0;
    sc_out< sc_lv<32> > locate_matrix_d0;
    sc_out< sc_lv<8> > conv_out_2_address0;
    sc_out< sc_logic > conv_out_2_ce0;
    sc_in< sc_lv<32> > conv_out_2_q0;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<5> > ap_var_for_const1;


    // Module declarations
    MaxPool2d(sc_module_name name);
    SC_HAS_PROCESS(MaxPool2d);

    ~MaxPool2d();

    sc_trace_file* mVcdFile;

    forw_back_sitofp_dEe<1,6,32,32>* forw_back_sitofp_dEe_U20;
    forw_back_fcmp_32eOg<1,2,32,32,1>* forw_back_fcmp_32eOg_U21;
    sc_signal< sc_lv<24> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<32> > grp_fu_185_p1;
    sc_signal< sc_lv<32> > reg_195;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_logic > ap_CS_fsm_state23;
    sc_signal< sc_lv<3> > i_fu_207_p2;
    sc_signal< sc_lv<3> > i_reg_565;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<32> > zext_ln41_fu_221_p1;
    sc_signal< sc_lv<32> > zext_ln41_reg_570;
    sc_signal< sc_lv<1> > icmp_ln38_fu_201_p2;
    sc_signal< sc_lv<32> > zext_ln41_4_fu_235_p1;
    sc_signal< sc_lv<32> > zext_ln41_4_reg_575;
    sc_signal< sc_lv<7> > sub_ln45_fu_251_p2;
    sc_signal< sc_lv<7> > sub_ln45_reg_580;
    sc_signal< sc_lv<3> > j_fu_267_p2;
    sc_signal< sc_lv<3> > j_reg_588;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<32> > zext_ln42_fu_281_p1;
    sc_signal< sc_lv<32> > zext_ln42_reg_593;
    sc_signal< sc_lv<1> > icmp_ln39_fu_261_p2;
    sc_signal< sc_lv<32> > zext_ln42_2_fu_291_p1;
    sc_signal< sc_lv<32> > zext_ln42_2_reg_598;
    sc_signal< sc_lv<6> > output_matrix_addr_reg_603;
    sc_signal< sc_lv<6> > locate_matrix_addr_reg_608;
    sc_signal< sc_lv<32> > sub_ln43_fu_327_p2;
    sc_signal< sc_lv<32> > sub_ln43_reg_616;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<1> > icmp_ln41_fu_310_p2;
    sc_signal< sc_lv<32> > col_2_fu_338_p2;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<1> > icmp_ln42_fu_333_p2;
    sc_signal< sc_lv<32> > add_ln43_fu_344_p2;
    sc_signal< sc_lv<32> > add_ln43_reg_629;
    sc_signal< sc_lv<32> > conv_out_2_load_reg_639;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<1> > icmp_ln43_5_fu_372_p2;
    sc_signal< sc_lv<1> > icmp_ln43_5_reg_645;
    sc_signal< sc_lv<1> > icmp_ln43_6_fu_378_p2;
    sc_signal< sc_lv<1> > icmp_ln43_6_reg_650;
    sc_signal< sc_lv<8> > tmp_V_fu_387_p4;
    sc_signal< sc_lv<8> > tmp_V_reg_655;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_lv<23> > tmp_V_2_fu_397_p1;
    sc_signal< sc_lv<23> > tmp_V_2_reg_661;
    sc_signal< sc_lv<1> > and_ln43_2_fu_429_p2;
    sc_signal< sc_lv<1> > and_ln43_2_reg_666;
    sc_signal< sc_lv<1> > p_Result_s_reg_670;
    sc_signal< sc_lv<32> > p_Val2_11_fu_536_p3;
    sc_signal< sc_lv<32> > p_Val2_11_reg_675;
    sc_signal< sc_logic > ap_CS_fsm_state17;
    sc_signal< sc_lv<32> > tmp_7_reg_681;
    sc_signal< sc_lv<32> > row_2_fu_556_p2;
    sc_signal< sc_logic > ap_CS_fsm_state18;
    sc_signal< sc_lv<3> > i_0_reg_107;
    sc_signal< sc_lv<3> > j_0_reg_118;
    sc_signal< sc_logic > ap_CS_fsm_state24;
    sc_signal< sc_lv<32> > max_num_0_reg_129;
    sc_signal< sc_lv<32> > col_0_reg_141;
    sc_signal< sc_lv<32> > max_num_1_reg_151;
    sc_signal< sc_lv<32> > ap_phi_mux_max_num_2_phi_fu_177_p4;
    sc_signal< sc_lv<32> > row_0_reg_163;
    sc_signal< sc_lv<32> > p_Val2_12_fu_549_p3;
    sc_signal< sc_lv<32> > max_num_2_reg_173;
    sc_signal< sc_lv<64> > zext_ln45_fu_304_p1;
    sc_signal< sc_lv<64> > sext_ln43_fu_349_p1;
    sc_signal< sc_lv<32> > grp_fu_185_p0;
    sc_signal< sc_lv<4> > col_fu_213_p3;
    sc_signal< sc_lv<4> > add_ln41_fu_229_p2;
    sc_signal< sc_lv<6> > shl_ln_fu_239_p3;
    sc_signal< sc_lv<7> > zext_ln45_2_fu_247_p1;
    sc_signal< sc_lv<7> > zext_ln41_3_fu_225_p1;
    sc_signal< sc_lv<4> > row_fu_273_p3;
    sc_signal< sc_lv<4> > add_ln42_fu_285_p2;
    sc_signal< sc_lv<7> > j_0_cast3_fu_257_p1;
    sc_signal< sc_lv<7> > add_ln45_fu_295_p2;
    sc_signal< sc_lv<32> > sext_ln45_fu_300_p1;
    sc_signal< sc_lv<32> > shl_ln43_fu_315_p2;
    sc_signal< sc_lv<32> > shl_ln43_2_fu_321_p2;
    sc_signal< sc_lv<32> > bitcast_ln43_2_fu_354_p1;
    sc_signal< sc_lv<8> > tmp_14_fu_358_p4;
    sc_signal< sc_lv<23> > trunc_ln43_2_fu_368_p1;
    sc_signal< sc_lv<32> > p_Val2_s_fu_384_p1;
    sc_signal< sc_lv<1> > icmp_ln43_4_fu_407_p2;
    sc_signal< sc_lv<1> > icmp_ln43_fu_401_p2;
    sc_signal< sc_lv<1> > or_ln43_fu_413_p2;
    sc_signal< sc_lv<1> > or_ln43_2_fu_419_p2;
    sc_signal< sc_lv<1> > and_ln43_fu_423_p2;
    sc_signal< sc_lv<1> > grp_fu_190_p2;
    sc_signal< sc_lv<25> > mantissa_V_fu_443_p4;
    sc_signal< sc_lv<9> > zext_ln339_fu_456_p1;
    sc_signal< sc_lv<9> > add_ln339_fu_459_p2;
    sc_signal< sc_lv<8> > sub_ln1311_fu_473_p2;
    sc_signal< sc_lv<1> > isNeg_fu_465_p3;
    sc_signal< sc_lv<9> > sext_ln1311_fu_478_p1;
    sc_signal< sc_lv<9> > ush_fu_482_p3;
    sc_signal< sc_lv<32> > sext_ln1311_2_fu_490_p1;
    sc_signal< sc_lv<25> > sext_ln1311_3_fu_494_p1;
    sc_signal< sc_lv<79> > zext_ln682_fu_452_p1;
    sc_signal< sc_lv<79> > zext_ln1287_fu_498_p1;
    sc_signal< sc_lv<25> > r_V_fu_502_p2;
    sc_signal< sc_lv<1> > tmp_9_fu_514_p3;
    sc_signal< sc_lv<79> > r_V_2_fu_508_p2;
    sc_signal< sc_lv<32> > zext_ln662_fu_522_p1;
    sc_signal< sc_lv<32> > tmp_11_fu_526_p4;
    sc_signal< sc_lv<32> > result_V_2_fu_544_p2;
    sc_signal< sc_lv<24> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<24> ap_ST_fsm_state1;
    static const sc_lv<24> ap_ST_fsm_state2;
    static const sc_lv<24> ap_ST_fsm_state3;
    static const sc_lv<24> ap_ST_fsm_state4;
    static const sc_lv<24> ap_ST_fsm_state5;
    static const sc_lv<24> ap_ST_fsm_state6;
    static const sc_lv<24> ap_ST_fsm_state7;
    static const sc_lv<24> ap_ST_fsm_state8;
    static const sc_lv<24> ap_ST_fsm_state9;
    static const sc_lv<24> ap_ST_fsm_state10;
    static const sc_lv<24> ap_ST_fsm_state11;
    static const sc_lv<24> ap_ST_fsm_state12;
    static const sc_lv<24> ap_ST_fsm_state13;
    static const sc_lv<24> ap_ST_fsm_state14;
    static const sc_lv<24> ap_ST_fsm_state15;
    static const sc_lv<24> ap_ST_fsm_state16;
    static const sc_lv<24> ap_ST_fsm_state17;
    static const sc_lv<24> ap_ST_fsm_state18;
    static const sc_lv<24> ap_ST_fsm_state19;
    static const sc_lv<24> ap_ST_fsm_state20;
    static const sc_lv<24> ap_ST_fsm_state21;
    static const sc_lv<24> ap_ST_fsm_state22;
    static const sc_lv<24> ap_ST_fsm_state23;
    static const sc_lv<24> ap_ST_fsm_state24;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_FFFFFC19;
    static const sc_lv<3> ap_const_lv3_6;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<4> ap_const_lv4_2;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<23> ap_const_lv23_0;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<9> ap_const_lv9_181;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<8> ap_const_lv8_7F;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_37;
    static const sc_lv<5> ap_const_lv5_2;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_clk_no_reset_();
    void thread_add_ln339_fu_459_p2();
    void thread_add_ln41_fu_229_p2();
    void thread_add_ln42_fu_285_p2();
    void thread_add_ln43_fu_344_p2();
    void thread_add_ln45_fu_295_p2();
    void thread_and_ln43_2_fu_429_p2();
    void thread_and_ln43_fu_423_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state18();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state23();
    void thread_ap_CS_fsm_state24();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_phi_mux_max_num_2_phi_fu_177_p4();
    void thread_ap_ready();
    void thread_bitcast_ln43_2_fu_354_p1();
    void thread_col_2_fu_338_p2();
    void thread_col_fu_213_p3();
    void thread_conv_out_2_address0();
    void thread_conv_out_2_ce0();
    void thread_grp_fu_185_p0();
    void thread_i_fu_207_p2();
    void thread_icmp_ln38_fu_201_p2();
    void thread_icmp_ln39_fu_261_p2();
    void thread_icmp_ln41_fu_310_p2();
    void thread_icmp_ln42_fu_333_p2();
    void thread_icmp_ln43_4_fu_407_p2();
    void thread_icmp_ln43_5_fu_372_p2();
    void thread_icmp_ln43_6_fu_378_p2();
    void thread_icmp_ln43_fu_401_p2();
    void thread_isNeg_fu_465_p3();
    void thread_j_0_cast3_fu_257_p1();
    void thread_j_fu_267_p2();
    void thread_locate_matrix_address0();
    void thread_locate_matrix_ce0();
    void thread_locate_matrix_d0();
    void thread_locate_matrix_we0();
    void thread_mantissa_V_fu_443_p4();
    void thread_or_ln43_2_fu_419_p2();
    void thread_or_ln43_fu_413_p2();
    void thread_output_matrix_address0();
    void thread_output_matrix_ce0();
    void thread_output_matrix_d0();
    void thread_output_matrix_we0();
    void thread_p_Val2_11_fu_536_p3();
    void thread_p_Val2_12_fu_549_p3();
    void thread_p_Val2_s_fu_384_p1();
    void thread_r_V_2_fu_508_p2();
    void thread_r_V_fu_502_p2();
    void thread_result_V_2_fu_544_p2();
    void thread_row_2_fu_556_p2();
    void thread_row_fu_273_p3();
    void thread_sext_ln1311_2_fu_490_p1();
    void thread_sext_ln1311_3_fu_494_p1();
    void thread_sext_ln1311_fu_478_p1();
    void thread_sext_ln43_fu_349_p1();
    void thread_sext_ln45_fu_300_p1();
    void thread_shl_ln43_2_fu_321_p2();
    void thread_shl_ln43_fu_315_p2();
    void thread_shl_ln_fu_239_p3();
    void thread_sub_ln1311_fu_473_p2();
    void thread_sub_ln43_fu_327_p2();
    void thread_sub_ln45_fu_251_p2();
    void thread_tmp_11_fu_526_p4();
    void thread_tmp_14_fu_358_p4();
    void thread_tmp_9_fu_514_p3();
    void thread_tmp_V_2_fu_397_p1();
    void thread_tmp_V_fu_387_p4();
    void thread_trunc_ln43_2_fu_368_p1();
    void thread_ush_fu_482_p3();
    void thread_zext_ln1287_fu_498_p1();
    void thread_zext_ln339_fu_456_p1();
    void thread_zext_ln41_3_fu_225_p1();
    void thread_zext_ln41_4_fu_235_p1();
    void thread_zext_ln41_fu_221_p1();
    void thread_zext_ln42_2_fu_291_p1();
    void thread_zext_ln42_fu_281_p1();
    void thread_zext_ln45_2_fu_247_p1();
    void thread_zext_ln45_fu_304_p1();
    void thread_zext_ln662_fu_522_p1();
    void thread_zext_ln682_fu_452_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
