-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Padding_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_matrix_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    input_matrix_ce0 : OUT STD_LOGIC;
    input_matrix_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_matrix_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    output_matrix_ce0 : OUT STD_LOGIC;
    output_matrix_we0 : OUT STD_LOGIC;
    output_matrix_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    output_matrix_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    output_matrix_ce1 : OUT STD_LOGIC;
    output_matrix_we1 : OUT STD_LOGIC;
    output_matrix_d1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of Padding_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv5_1A : STD_LOGIC_VECTOR (4 downto 0) := "11010";
    constant ap_const_lv6_3E : STD_LOGIC_VECTOR (5 downto 0) := "111110";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv10_310 : STD_LOGIC_VECTOR (9 downto 0) := "1100010000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_1C : STD_LOGIC_VECTOR (4 downto 0) := "11100";
    constant ap_const_lv5_1E : STD_LOGIC_VECTOR (4 downto 0) := "11110";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal indvar_flatten_reg_108 : STD_LOGIC_VECTOR (9 downto 0);
    signal i_0_reg_119 : STD_LOGIC_VECTOR (4 downto 0);
    signal j_0_reg_130 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln89_fu_233_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln89_fu_239_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal select_ln89_fu_391_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal and_ln91_1_fu_433_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln91_1_reg_497 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_141_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln92_3_reg_506 : STD_LOGIC_VECTOR (10 downto 0);
    signal j_fu_469_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal zext_ln94_fu_443_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal sext_ln92_fu_464_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln92_fu_478_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sub_ln94_mid2_fu_299_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln90_mid2_cast_fu_386_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln_fu_149_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln94_1_fu_161_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln94_1_fu_157_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln94_2_fu_169_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal i_0_cast7_fu_145_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln92_fu_185_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln92_1_fu_199_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln3_fu_191_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln92_1_fu_207_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_fu_217_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln90_fu_251_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_245_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal shl_ln94_mid1_fu_269_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln94_1_mid1_fu_281_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln94_3_fu_277_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln94_4_fu_289_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln94_1_fu_293_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln94_fu_173_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln91_2_fu_308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln91_fu_179_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_0_cast7_mid1_fu_265_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln92_4_fu_322_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln92_1_mid1_fu_336_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln92_mid1_fu_328_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln92_3_fu_344_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln92_1_fu_348_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln92_fu_211_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_1_fu_362_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln91_4_fu_372_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln91_1_fu_227_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_0_mid2_fu_257_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_399_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln91_5_fu_409_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln91_1_mid2_fu_378_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln91_3_fu_415_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln91_mid2_fu_314_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln91_2_fu_427_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln91_fu_421_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln94_fu_439_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln92_1_fu_448_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln92_1_fu_454_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln92_mid2_fu_354_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln92_2_fu_458_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln92_2_fu_475_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_0_reg_119_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln89_fu_233_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                i_0_reg_119 <= select_ln89_fu_391_p3;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_0_reg_119 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln89_fu_233_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten_reg_108 <= add_ln89_fu_239_p2;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                indvar_flatten_reg_108 <= ap_const_lv10_0;
            end if; 
        end if;
    end process;

    j_0_reg_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln89_fu_233_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                j_0_reg_130 <= j_fu_469_p2;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                j_0_reg_130 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln91_1_fu_433_p2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln89_fu_233_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln92_3_reg_506 <= grp_fu_141_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln89_fu_233_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and_ln91_1_reg_497 <= and_ln91_1_fu_433_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln89_fu_233_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln89_fu_233_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln89_fu_233_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln89_fu_239_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_108) + unsigned(ap_const_lv10_1));
    add_ln92_1_fu_448_p2 <= std_logic_vector(unsigned(j_0_mid2_fu_257_p3) + unsigned(ap_const_lv5_1E));
    add_ln92_2_fu_458_p2 <= std_logic_vector(unsigned(zext_ln92_1_fu_454_p1) + unsigned(sub_ln92_mid2_fu_354_p3));
    add_ln92_4_fu_322_p2 <= std_logic_vector(unsigned(i_0_cast7_mid1_fu_265_p1) + unsigned(ap_const_lv6_3E));
    add_ln92_fu_185_p2 <= std_logic_vector(unsigned(i_0_cast7_fu_145_p1) + unsigned(ap_const_lv6_3E));
    and_ln91_1_fu_433_p2 <= (and_ln91_fu_421_p2 and and_ln91_2_fu_427_p2);
    and_ln91_2_fu_427_p2 <= (icmp_ln91_mid2_fu_314_p3 and icmp_ln91_3_fu_415_p2);
    and_ln91_fu_421_p2 <= (icmp_ln91_5_fu_409_p2 and icmp_ln91_1_mid2_fu_378_p3);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state4 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln89_fu_233_p2)
    begin
        if ((icmp_ln89_fu_233_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_141_p2 <= std_logic_vector(unsigned(sub_ln94_mid2_fu_299_p3) + unsigned(zext_ln90_mid2_cast_fu_386_p1));
    i_0_cast7_fu_145_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_0_reg_119),6));
    i_0_cast7_mid1_fu_265_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_fu_245_p2),6));
    i_fu_245_p2 <= std_logic_vector(unsigned(i_0_reg_119) + unsigned(ap_const_lv5_1));
    icmp_ln89_fu_233_p2 <= "1" when (indvar_flatten_reg_108 = ap_const_lv10_310) else "0";
    icmp_ln90_fu_251_p2 <= "1" when (j_0_reg_130 = ap_const_lv5_1C) else "0";
    icmp_ln91_1_fu_227_p2 <= "0" when (tmp_fu_217_p4 = ap_const_lv4_0) else "1";
    icmp_ln91_1_mid2_fu_378_p3 <= 
        icmp_ln91_4_fu_372_p2 when (icmp_ln90_fu_251_p2(0) = '1') else 
        icmp_ln91_1_fu_227_p2;
    icmp_ln91_2_fu_308_p2 <= "1" when (unsigned(i_fu_245_p2) < unsigned(ap_const_lv5_1A)) else "0";
    icmp_ln91_3_fu_415_p2 <= "1" when (unsigned(j_0_mid2_fu_257_p3) < unsigned(ap_const_lv5_1A)) else "0";
    icmp_ln91_4_fu_372_p2 <= "0" when (tmp_1_fu_362_p4 = ap_const_lv4_0) else "1";
    icmp_ln91_5_fu_409_p2 <= "0" when (tmp_2_fu_399_p4 = ap_const_lv4_0) else "1";
    icmp_ln91_fu_179_p2 <= "1" when (unsigned(i_0_reg_119) < unsigned(ap_const_lv5_1A)) else "0";
    icmp_ln91_mid2_fu_314_p3 <= 
        icmp_ln91_2_fu_308_p2 when (icmp_ln90_fu_251_p2(0) = '1') else 
        icmp_ln91_fu_179_p2;
    input_matrix_address0 <= sext_ln92_fu_464_p1(10 - 1 downto 0);

    input_matrix_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_matrix_ce0 <= ap_const_logic_1;
        else 
            input_matrix_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    j_0_mid2_fu_257_p3 <= 
        ap_const_lv5_0 when (icmp_ln90_fu_251_p2(0) = '1') else 
        j_0_reg_130;
    j_fu_469_p2 <= std_logic_vector(unsigned(j_0_mid2_fu_257_p3) + unsigned(ap_const_lv5_1));
    output_matrix_address0 <= zext_ln94_fu_443_p1(10 - 1 downto 0);
    output_matrix_address1 <= zext_ln92_fu_478_p1(10 - 1 downto 0);

    output_matrix_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            output_matrix_ce0 <= ap_const_logic_1;
        else 
            output_matrix_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    output_matrix_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            output_matrix_ce1 <= ap_const_logic_1;
        else 
            output_matrix_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    output_matrix_d0 <= ap_const_lv32_0;
    output_matrix_d1 <= input_matrix_q0;

    output_matrix_we0_assign_proc : process(icmp_ln89_fu_233_p2, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0, and_ln91_1_fu_433_p2)
    begin
        if (((ap_const_lv1_0 = and_ln91_1_fu_433_p2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln89_fu_233_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            output_matrix_we0 <= ap_const_logic_1;
        else 
            output_matrix_we0 <= ap_const_logic_0;
        end if; 
    end process;


    output_matrix_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, and_ln91_1_reg_497, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_lv1_1 = and_ln91_1_reg_497) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            output_matrix_we1 <= ap_const_logic_1;
        else 
            output_matrix_we1 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln89_fu_391_p3 <= 
        i_fu_245_p2 when (icmp_ln90_fu_251_p2(0) = '1') else 
        i_0_reg_119;
        sext_ln92_1_fu_207_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln92_1_fu_199_p3),11));

        sext_ln92_2_fu_475_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln92_3_reg_506),32));

        sext_ln92_3_fu_344_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln92_1_mid1_fu_336_p3),11));

        sext_ln92_fu_464_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln92_2_fu_458_p2),64));

        sext_ln94_fu_439_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_141_p2),32));

    shl_ln3_fu_191_p3 <= (add_ln92_fu_185_p2 & ap_const_lv5_0);
    shl_ln92_1_fu_199_p3 <= (add_ln92_fu_185_p2 & ap_const_lv3_0);
    shl_ln92_1_mid1_fu_336_p3 <= (add_ln92_4_fu_322_p2 & ap_const_lv3_0);
    shl_ln92_mid1_fu_328_p3 <= (add_ln92_4_fu_322_p2 & ap_const_lv5_0);
    shl_ln94_1_fu_161_p3 <= (i_0_reg_119 & ap_const_lv2_0);
    shl_ln94_1_mid1_fu_281_p3 <= (i_fu_245_p2 & ap_const_lv2_0);
    shl_ln94_mid1_fu_269_p3 <= (i_fu_245_p2 & ap_const_lv5_0);
    shl_ln_fu_149_p3 <= (i_0_reg_119 & ap_const_lv5_0);
    sub_ln92_1_fu_348_p2 <= std_logic_vector(unsigned(shl_ln92_mid1_fu_328_p3) - unsigned(sext_ln92_3_fu_344_p1));
    sub_ln92_fu_211_p2 <= std_logic_vector(unsigned(shl_ln3_fu_191_p3) - unsigned(sext_ln92_1_fu_207_p1));
    sub_ln92_mid2_fu_354_p3 <= 
        sub_ln92_1_fu_348_p2 when (icmp_ln90_fu_251_p2(0) = '1') else 
        sub_ln92_fu_211_p2;
    sub_ln94_1_fu_293_p2 <= std_logic_vector(unsigned(zext_ln94_3_fu_277_p1) - unsigned(zext_ln94_4_fu_289_p1));
    sub_ln94_fu_173_p2 <= std_logic_vector(unsigned(zext_ln94_1_fu_157_p1) - unsigned(zext_ln94_2_fu_169_p1));
    sub_ln94_mid2_fu_299_p3 <= 
        sub_ln94_1_fu_293_p2 when (icmp_ln90_fu_251_p2(0) = '1') else 
        sub_ln94_fu_173_p2;
    tmp_1_fu_362_p4 <= i_fu_245_p2(4 downto 1);
    tmp_2_fu_399_p4 <= j_0_mid2_fu_257_p3(4 downto 1);
    tmp_fu_217_p4 <= i_0_reg_119(4 downto 1);
    zext_ln90_mid2_cast_fu_386_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_0_mid2_fu_257_p3),11));
    zext_ln92_1_fu_454_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln92_1_fu_448_p2),11));
    zext_ln92_fu_478_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln92_2_fu_475_p1),64));
    zext_ln94_1_fu_157_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_149_p3),11));
    zext_ln94_2_fu_169_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln94_1_fu_161_p3),11));
    zext_ln94_3_fu_277_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln94_mid1_fu_269_p3),11));
    zext_ln94_4_fu_289_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln94_1_mid1_fu_281_p3),11));
    zext_ln94_fu_443_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln94_fu_439_p1),64));
end behav;
